name: Deploy on Apache server over SSH
on: 
  push:
    branches:
        - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Remove all git files
      run: rm -rf .git*
    - name: Deploy files via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        local_path: ./
        remote_path: /var/deploy/iefrei-remastered 
        sftpArgs: '-o ConnectTimeout=5'
        sftp_only: false
        delete_remote_files: yes

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            echo "Creating .env file"
            cat <<EOF > /var/deploy/iefrei-remastered/.env
            ${{ secrets.ENV_FILE }}
            EOF

            echo "Checking if the db file exists"
            ls /var/databases/iefrei.db || sqlite3 /var/databases/iefrei.db "VACUUM;"
            echo "游릭 Database file checked"

            cd /var/deploy/iefrei-remastered

            echo "Stopping and removing old container if exists"
            sudo docker stop iefrei-remastered || true
            sudo docker rm iefrei-remastered || true
            echo "游릭 Old container stopped and removed"

            echo "Checking if the Docker image exists"
            sudo docker image rm iefrei-remastered || true
            echo "游릭 Docker image checked"

            echo "Building Docker image..."
            sudo docker build -t iefrei-remastered . --no-cache
            echo "游릭 Docker image built successfully"

            echo "Running the new Docker container"
            sudo docker run -d \
            -v /var/courses:/app/courses \
            -v /var/databases/iefrei.db:/app/iefrei.db \
            -p 5010:5010 \
            --name iefrei-remastered \
            iefrei-remastered
            echo "游릭 New container running"

            echo "Checking if the container is running"
            sudo docker ps | grep iefrei-remastered
            echo "游릭 Container is running"